version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    working_directory: /home/ubuntu/working
    steps:
        - checkout
        - run: pip install -U -r requirements.txt
        - run: python setup.py sdist
        - run: pip install twine
        - run: echo $TWINE_USERNAME
        - run: twine upload dist/*
        - run: sed -i.bak s/BUILD_NUMBER/$CIRCLE_BUILD_NUM/g installer.cfg
        - run: pynsist installer.cfg
        - store_artifacts:
            path: build/nsis